### ISSUE TITLE
Add ability to rotate shapes

### ISSUE THREAD

**Issue by bridget512** [JamesBakerMM/TeachAndDraw#53]
**Request**
Request to add the ability to rotate basic shapes. Currently only images/sprites can use the rotation.

**Reason**
Adding shapes will be one of the first things a student will attempt when learning a new library. The ability for them to test how rotation works in the library without adding the complexity of adding images/sprites to use the rotation feature would be beneficial.

**Comment by JamesBakerMM** [comment]
fixed by @mellic03  in [efddf6c](https://github.com/JamesBakerMM/TeachAndDraw/commit/efddf6ce9d74efb9a78e8979d1c135bc4cf0b205)
