### ISSUE TITLE
math.atan2 function does not adjust degrees when called

### ISSUE THREAD

**Issue by NickBland** [JamesBakerMM/TeachAndDraw#68]
Expected behaviour: calling $.math.atan2(y, x) should return the angle from two points, adjusted for 0 degrees being the top
![Screenshot 2024-07-21 142128](https://github.com/user-attachments/assets/d8e765c2-e66c-48a2-8a5c-df242cc24621)

Current behaviour: result returned is 90 degrees clockwise off what it should be, resulting in unexpected behaviour
![Screenshot 2024-07-21 141928](https://github.com/user-attachments/assets/757c4f3f-6c41-4409-9ff5-b7f4aa119806)

quick work around is to wrap the atan2 (yes there is a spelling mistake currently there) in $.math.adjustDegressSoTopIsZero()

**Comment by JamesBakerMM** [comment]
This is actually an issue with how our library is forcing degrees to be 0. Atan2 is built around assuming 0 is to the right, while I could then offset it. It'd mean if someone checked the atan2 output it'd always be off by 90 which would look silly.

I may have to remove the atan2 method and instead give the collider or maths a .faceTo method  or a .getFacingAngle method or similar something that lets students achieve the "I want to get the number for this direction from where I am".

**Comment by andrewparoz** [comment]
I would definitely not rewrite atan2 or hide it, atan2 is a maths function and is used from the x axis. Write your own from the top sure, but don't block actual atan2, it's important for lots of things.

**Comment by JamesBakerMM** [comment]
I more meant remove our degree oriented version from maffs.js and instead give colliders a .getFacingAngle method or similar.

**Comment by JamesBakerMM** [comment]
Problem has been worked around by adding getAngleToPoint as a method on Entities to achieve the usecase :)
