### ISSUE TITLE
Colour Regex fails on css colour words currently

### ISSUE THREAD

**Issue by JamesBakerMM** [JamesBakerMM/TeachAndDraw#88]
Colour regex seems to fail on colour words. @NickBland I vaguely recall a discussion involving the regex and the css colour words. 

Was it altered so css colour words fail or am I misremembering?

**Comment by NickBland** [comment]
it should work :tm: with css colour words, as that was a part of the regex. was there something with caps?

**Comment by NickBland** [comment]
The issue is with the way JS implements the .test() method, in that it is iterative when certain flags are applied. Since we need the g flag for testing, the solution is to add a line to always compare to the first iteration of the regex.
